### ISSUE TITLE
Asignación de Título y Descripción para TFG

### ISSUE THREAD

**Issue by jbs1009** [jbs1009/TFG_GIS_Jorge_Bermejo_Sacristan#6]

**Comment by jbs1009** [comment]
En vista de estos artículos, un posible título inicial para el TFG podría ser: "Análisis genético a partir de secuenciación masiva de secuencias relacionadas con la enfermedad de Parkinson"

Una posible descripción inicial y general podría ser: Proyecto destinado a la implementación de un pipeline que permita el análisis bioinformático de una secuenciación masiva de secuencias genéticas relacionadas con la enfermedad de Parkinson.

**Comment by JoseBarbero** [comment]
Una alternativa al título para centrar un poco más el tiro, a ver qué os parece: "Pipeline bioinformático para el análisis de datos genómicos de secuenciación masiva relacionados con la enfermedad de Parkinson".

**Comment by jbs1009** [comment]
Buenos días, @JoseBarbero @SoniaRamosGomez 
Me parece una alternativa bastante acertada para el proyecto al concretar mejor la línea del mismo. Esperemos a ver qué opina Sonia o si tiene alguna otra sugerencia.

En cuanto a la descripción que propuse, ¿os parece suficiente o sería necesario ampliarla? De nuevo, estoy abierto a todo tipo de sugerencias que tengáis.

**Comment by SoniaRamosGomez** [comment]
Buenos días @JoseBarbero @jbs1009 ,
Os hago la siguiente propuesta de mejora, si os parece correcta se lo envío hoy mismo a José Francisco y @jbs1009 cierra esta issue:

**Titulo**:"Pipeline bioinformático para el análisis de datos genómicos de secuenciación masiva relacionados con la enfermedad de Parkinson"
**Resumen**: Proyecto destinado a la implementación de un pipeline que permita el análisis bioinformático de secuenciación masiva de datos genómicos relacionados con la enfermedad de Parkinson, con la finalidad de analizar y caracterizar diferentes variantes funcionales y/o estructurales otorgando un significado biológico a las mismas.
**Tutores**: José Antonio Barbero Aparicio y Sonia Ramos Gómez
**Alumno**: Jorge Bermejo Sacristán

**Comment by JoseBarbero** [comment]
Gracias, Sonia. Lo veo perfecto.

**Comment by jbs1009** [comment]
Por mi parte, también perfecto. Muchas gracias.

**Comment by SoniaRamosGomez** [comment]
@jbs1009 considera esta issue para cerrar
